/* eslint-disable max-len */
export default {
  up: queryInterface => queryInterface.bulkInsert('Articles', [
    {
      userId: 9,
      slug: 'creat-sample',
      title: 'browser',
      body:
          'Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userId: 10,
      slug: 'ju-man',
      title: 'browser',
      body:
          'Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel.',
      createdAt: new Date(),
      updatedAt: new Date()
    },
    {
      userId: 1,
      slug: 'rambo-team',
      title: 'browser',
      body:
          'Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel. Modi sequi veritatis nulla autem quis libero possimus molestiae est. Eum provident et ullam officia aut eum. Dolorem rerum quasi neque non exercitationem harum qui. Illo adipisci porro in vero quam. Consequuntur asperiores harum ut non. Molestias doloribus sunt consequatur temporibus ut. Soluta maxime pariatur. Et quia voluptas eum ut. Quo a repellat quia maiores. Ipsum vitae voluptas reprehenderit doloribus. Eos sapiente non. Odio qui et molestiae sint explicabo. Dolorem aliquam ullam consequatur sunt sapiente omnis et vel.',
      createdAt: new Date(),
      updatedAt: new Date()
    }
  ]),
  down: queryInterface => queryInterface.bulkDelete('Articles', null, {})
};
