openapi: 3.0.1

info:
  title: Authors Haven API Documentation
  description: Create a community of like minded authors to foster inspiration and innovation by leveraging the modern web.
  version: 1.0.0
  contact:
    email: teamrambo50@gmail.com

license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /
    desription: Localhost server
  - url: https://authors-haven-development.herokuapp.com/
    desription: Heroku development server

paths:
  /:
    summary: Represent root of the application
    description: Represent root of the application.
    get:
      summary: Returns a welcome message.
      description: Returns a welcome message.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to Authors Haven
  /api/v1/users:
    post:
      summary: Route for signing new users up
      description: Allow new users to register to use the application on providing valid details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/UserSignUp'
        description: user to be created
      responses:
        201:
          description: new user created successfully
        409:
          description: Conflict. Email or username exists
        500:
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  UserSignUp:
    type: object
    required:
    - firstName
    - lastName
    - userName
    - email
    - password
    properties:
      firstName:
        type: string
        example: Rihanna
      lastName:
        type: string
        example: Adeyemo
      userName:
        type: string
        example: Riri
      email:
        type: string
        example: riri.adeyemo@andela.com
      password:
        type: string
        example: incorrect
