openapi: 3.0.1

info:
  title: Authors Haven API Documentation
  description: Create a community of like minded authors to foster inspiration and innovation by leveraging the modern web.
  version: 1.0.0
  contact:
    email: teamrambo50@gmail.com

license:
  name: Apache 2.0
  url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: /
    desription: Localhost server
  - url: https://authors-haven-development.herokuapp.com/
    desription: Heroku development server

paths:
  /:
    summary: Represent root of the application
    description: Represent root of the application.
    get:
      summary: Returns a welcome message.
      description: Returns a welcome message.
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to Authors Haven

  "/api/v1/sessions/create":
    summary: Login Route
    post:
      description: Login Route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                userLogin:
                  type: string
                  minLength: 2
                  example: adechukwu
                password:
                  type: string
                  minLength: 4
                  example: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/loginResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponse"
        '403':
          description: Incorrect username or password
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponse"
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/serverResponse"

  "/api/v1/sessions/{token}/destroy":
    summary: Signout Route
    patch:
      description: Signout Route
      parameters:
        - name: token
          in: path
          description: Enter User Token
          required: true
          schema:
            type: string
            format: int64
      responses:
        "200":
          description: Signout successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/signoutResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponse"
        "403":
          description: Incorrect username or password
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errorResponse"
        "500":
          description: Server Error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/serverResponse"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    loginResponse:
      type: object
      properties:
        user:
          type: object
    errorResponse:
      type: object
      properties:
        message:
          type: string
    serverResponse:
      type: object
      properties:
        error:
          type: string
    signoutResponse:
      type: object
      properties:
        message:
          type: string
